sudo: false
language: ruby
rvm:
- 2.3.1
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rspec spec
before_install: gem install bundler -v 1.16.3
deploy:
  provider: rubygems
  api_key:
    secure: jdniKr5kUszQJ1fATVM/1ChmvMMlYQovbPlrUZwxrKxV856qD6pvajhRCT7hJF9KIK7UIi5VEdFdjNKZhsztBIwpYwzmt4IsxiSOgXjDar2kH7Qer213Jx3tgWnu3NsbjBQy2l+QgefLnaxJEtxg3EFNNnD2/XInPhWrV8SRgn5YFPsyRNCXwLYAIMrZgeummKcpp3MeGXLt385sAJzgmQLaZjg2yyC7fbQ1Hh0ib/oU+6amfJV4aDRREWOdboxH+/c/FvNhT/P5lcZvNi/EGbkkG9OLWUguwcchE/vRBDosKWhx2mUqaBYwDet0eEbyNYfYMcaFB5/SjWLI+u0+ZKZ3oKQ+DKwQrWTPVBV6rPPpDrOOeEwQ0CnSpuoTCPJTCGPZCd0kk9O9k509+xQ479+Zo3BdkCREpk4fMKiH/2nNqU1o+lpzYNnnzeWjC5SLuJhxuUxuGEAhHyYK3rX3lL/ldxUp3TrcDfQ0fXMi5y7GM9QjYG6Z6gWP2S2e2J8tbjN3JfJM2iy3oHgFnoIHduu+phZYRsfMuN4vzFVJ8MN+Y651He6FHXq/pX9JXIbR/lZMPPITi+Tk2Rsmn+KFSYRpd1Ne2g8ZwGYPKeQt5xGcitGwpKPpLQlINpbqwDDaFo22tO68gVCBdiVboELz0pvexvzPOllKsPFDh4JhFhg=
  gem: active_job_log
  on:
    tags: true
    repo: platanus/active_job_log
